version: "3"
services:

  jenkins:
    build: jenkins
    user: ${USER_ID}
    volumes:
      #- devspace-jenkins:/var/jenkins_home
      - ./home:/var/jenkins_home
    environment:
      - JENKINS_OPTS= --argumentsRealm.passwd.${JENKINS_USERNAME}=${JENKINS_PASSWORD} --argumentsRealm.roles.${JENKINS_USERNAME}=admin

  git:
    build: git
    volumes:
      - /src
    command: 'true'

  pg:
    image: postgres
    volumes:
      - devspace-pgdata:/var/lib/postgresql/data

  testintegration:
    build:
      context: ./slave
      dockerfile: Dockerfile
      args:
        ICEVER: ice36
    volumes:
      - devspace-slave:/home/omero
    environment:
      - SLAVE_NAME=testintegration
      - SLAVE_EXECUTORS=2
      - SLAVE_PARAMS=-labels centos7 -labels ice36 -labels java18 -disableClientsUniqueId
      - WEB_PREFIX=/web
      - JENKINS_MASTER=http://jenkins:8080
      # - JENKINS_USERNAME=${JENKINS_USERNAME}
      # - JENKINS_PASSWORD=${JENKINS_PASSWORD}
    links:
      - jenkins
      - pg
      - seleniumhub
    #extra_hosts:
    #  - "testintegration:127.0.0.1"
    ports:
      - "14064"
      - "14063"

  omero:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        ICEVER: ice36
    volumes:
      - devspace-server:/home/omero
    environment:
      - SLAVE_NAME=omero
      - SLAVE_EXECUTORS=2
      - SLAVE_PARAMS=-labels centos7 -labels ice36 -labels java18 -disableClientsUniqueId
      - JENKINS_MASTER=http://jenkins:8080
      # - JENKINS_USERNAME=${JENKINS_USERNAME}
      # - JENKINS_PASSWORD=${JENKINS_PASSWORD}
    links:
      - jenkins
      - pg
    ports:
      - "4064"
      - "4063"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        ICEVER: noice
    volumes:
      - devspace-web:/home/omero
      - devspace-nginxconfd:/home/omero/nginx
    environment:
      - SLAVE_NAME=web
      - SLAVE_EXECUTORS=2
      - SLAVE_PARAMS= -labels centos7 -labels ice36 -labels java18 -disableClientsUniqueId
      - JENKINS_MASTER=http://jenkins:8080
      # - JENKINS_USERNAME=${JENKINS_USERNAME}
      # - JENKINS_PASSWORD=${JENKINS_PASSWORD}
      - WEB_PREFIX=/web
    links:
      - jenkins
      - redis
      - omero
      - testintegration

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - devspace-nginxconfd:/etc/nginx/conf.d
      - devspace-web:/home/omero
      - devspace-nginxlog:/var/log/nginx
      - ./nginx/sslcert:/etc/nginx/ssl:ro
    environment:
      - SLAVE_NAME=nginx
      - SLAVE_PARAMS=-labels centos7 -labels java -disableClientsUniqueId
      - JENKINS_MASTER=http://jenkins:8080
      # - JENKINS_USERNAME=${JENKINS_USERNAME}
      # - JENKINS_PASSWORD=${JENKINS_PASSWORD}
    links:
      - jenkins
      - web
    ports:
      - "80"
      - "443"

  nginxjenkins:
    image: nginx:1.10
    links:
      - jenkins
    volumes:
      - ./jenkins/conf.d:/etc/nginx/conf.d:ro
      - ./jenkins/sslcert:/etc/nginx/ssl:ro
    ports:
      - "443"

  redis:
    image: redis

  seleniumhub:
    image: selenium/hub:3.0.0-dubnium
    environment:
        - GRID_BROWSER_TIMEOUT=60
        - GRID_TIMEOUT=60
        - GRID_MAX_SESSION=2
        #- SE_OPTS=-browserTimeout 60 -timeout 60 maxSession 2
#    volumes:
#        - /dev/urandom:/dev/random
    ports:
      - "4444"

  seleniumfirefox:
    image: selenium/node-firefox:3.0.0-dubnium
    links:
        - seleniumhub:hub
#    volumes:
#        - /dev/shm:/dev/shm

  seleniumchrome:
    image: selenium/node-chrome:3.0.0-dubnium
    links:
        - seleniumhub:hub
#    volumes:
#        - /dev/shm:/dev/shm

volumes:
  devspace-pgdata:
  devspace-slave:
  devspace-server:
  devspace-web:
  devspace-nginxconfd:
  devspace-nginxlog:
